backend:
  name: git-gateway
  branch: main
  site_url: https://stupendous-quokka-9737db.netlify.app/

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "projeler"
    label: "Projeler"
    folder: "projeler"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Proje Adı", name: "title", widget: "string"}
      - {label: "Görsel", name: "image", widget: "image"}
      - {label: "Açıklama", name: "body", widget: "markdown"}
